version: '3.8'

services:
  rabbitmq:
    build: rabbitmq/
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq-data:/var
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"

volumes:
  rabbitmq-data:
