version: '3.8'

services:
  rabbitmq:
    build: rabbitmq/
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "myuser"
      RABBITMQ_DEFAULT_PASS: "mypassword"

  mongodb:
    image: mongo:5
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  elasticsearch:
    image: elasticsearch:8.5.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200

  kibana:
    image: kibana:8.5.1
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local

