version: '3.8'

services:
  sensor-data-processor:
    build: ../sensors-data-processor
    container_name: sensors-data-processor
    hostname: sensors-data-processor
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - mongodb
    environment:
      ELASTICSEARCH_HOSTNAME: "elasticsearch"
      ELASTICSEARCH_PORT: 9200
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: "myuser"
      SPRING_RABBITMQ_PASSWORD: "mypassword"
      SPRING_DATA_MONGODB_HOST: "mongodb"
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: "iot"
      SPRING_DATA_MONGODB_USERNAME: "admin"
      SPRING_DATA_MONGODB_PASSWORD: "secret"

  data-generator:
    build: ../sensors-data-generator
    container_name: data-generator
    hostname: data-generator
    depends_on:
      - rabbitmq
    environment:
      TENANT: "001"
      SENSOR_TOKEN: "123"
      BROKER_HOST: "rabbitmq"
      BROKER_PORT: 1883
      BROKER_USER: "myuser"
      BROKER_PASSWORD: "mypassword"
      RUN_MODE: "STREAM"
#      RUN_MODE: "ITERATION"
#      RUN_MODE: "RANGE"
      NUMBER_OF_ITERATIONS: 20000
      WATER_QUALITY_TOPIC: "building/floor_1/bedroom/water_quality"
      WEATHER_TOPIC: "building/weather"
      AIR_QUALITY_TOPIC: "building/001/air_quality"

  rabbitmq:
    build: rabbitmq/
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "myuser"
      RABBITMQ_DEFAULT_PASS: "mypassword"

  mongodb:
    image: mongo:5
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  elasticsearch:
    image: elasticsearch:8.5.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200

  kibana:
    image: kibana:8.5.1
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch

  mail:
    image: mailhog/mailhog
    container_name: mail
    hostname: mail
    ports:
      # web client
      - target: 8025
        published: 8025

volumes:
  es_data:
    driver: local

