version: '3.8'

services:
  rabbitmq:
    build: rabbitmq/
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "myuser"
      RABBITMQ_DEFAULT_PASS: "mypassword"
  mongodb:
    image: mongo:5
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
