spring:
  cloud:
    stream:
      bindings:
        input:
          destination: amq.topic
          binder: rabbitmqtt
          group: sensor-consumer-group
      rabbit:
        bindings:
          input:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: ".sensor"
      binders:
        rabbitmqtt:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: rabbitmq
                password: rabbitmq
