spring:

  data:
    mongodb:
      uri: ""
      username: ""
      password: ""

  rabbitmq:
    username: myuser
    password: mypassword

  cloud:
    stream:
      bindings:
        sensorDataConsumer-in-0:
          destination: amq.topic
          group: sensor.data.group
          consumer:
            queueNameGroupOnly: true
            bindingRoutingKey: ".sensor"
      rabbit:
        bindings:
          sensorDataConsumer-in-0:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: "*.sensor"

elasticsearch:
  host: ""
  port: ""
