spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: iot
      username: admin
      password: secret
      authentication-database: admin

  rabbitmq:
    username: myuser
    password: mypassword

  cloud:
    function:
      definition: weatherDataConsumer;waterQualityDataConsumer;airQualityDataConsumer
    stream:
      bindings:
        weatherDataConsumer-in-0:
          destination: amq.topic
          group: weather.data.group
        waterQualityDataConsumer-in-0:
          destination: amq.topic
          group: water_quality.data.group
        airQualityDataConsumer-in-0:
          destination: amq.topic
          group: air_quality.data.group
      rabbit:
        bindings:
          weatherDataConsumer-in-0:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: "#.weather"
          waterQualityDataConsumer-in-0:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: "#.water_quality"
          airQualityDataConsumer-in-0:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: "#.air_quality"

management:
  endpoints:
    web:
      exposure:
        include: "*"

elasticsearch:
  hostname: "localhost"
  port: "9200"
